### ISSUE TITLE
Add home and bottom navigation

### ISSUE THREAD

**Issue by alexandru-calinoiu** [code4romania/teacher-workout-android#29]
Let's add the basic home screen,

It should have a title and the navigation footer.

![image](https://user-images.githubusercontent.com/679198/134764331-f1c80de6-1bae-4c28-988f-66913f6e12ae.png)

The footer should be linked to a fragment in each of the features, 

- pressing 'Acasa' will navigate the user to features/learn/themes_fragment
- pressing 'Profil' will navigate the user to features/profile/profile_fragment

Getting started docs on how to use bottom nav with composable https://developer.android.com/jetpack/compose/navigation#bottom-nav

**Comment by AlexandraDamaschin** [comment]
I've start working on this.
