### ISSUE TITLE
Implement generic onboarding pages

### ISSUE THREAD

**Issue by catileptic** [code4romania/teacher-workout-android#5]
[The Figma document](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=0%3A1) contains the entire UI of the project. 

You can export any image (asset) directly from Figma. [Here's how](https://drive.google.com/file/d/1KJncuAGFvKEo6zrjC9H3O59auITE0q2h/view). 

**Please do not try to recreate the UI design exactly.** Prioritize using de default UI mobile components, and following the material design guidelines. The UI objects should be positioned roughly the same as in the Figma screens. 

[The mobile flow can be found in the project Wiki](https://github.com/code4romania/teacher-workout-backend/wiki/Teacher-Workout-Mobile-flow).

_Please define related colors and text & button styles in the corresponding values files. Please extract all text values in the corresponding xml files so we can easily adjust them. <3_

---

After having just created their account and after logging in, a user is redirected to the on-boarding pages. They can either go through the entire on-boarding process or skip it all together. If they do not skip nor complete the on-boarding process, they can't access any other screen in the app. 

We need these 3 generic on-boarding pages, which will later be populated by text describing the main functionalities of the app. 

![image](https://user-images.githubusercontent.com/14028425/123407944-2c106180-d5b5-11eb-81e0-b0df78bac9f0.png)

**Comment by AlexandraDamaschin** [comment]
Me and @corinaorasan are working on this issue.

**Comment by AlexandraDamaschin** [comment]
We tried to work on this but didn't finish it. Anyone, please feel free to give it a try.
