### ISSUE TITLE
Implement lesson themes screen

### ISSUE THREAD

**Issue by catileptic** [code4romania/teacher-workout-android#6]
[The Figma document](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=0%3A1) contains the entire UI of the project. 

You can export any image (asset) directly from Figma. [Here's how](https://drive.google.com/file/d/1KJncuAGFvKEo6zrjC9H3O59auITE0q2h/view). 

**Please do not try to recreate the UI design exactly.** Prioritize using de default UI mobile components, and following the material design guidelines. The UI objects should be positioned roughly the same as in the Figma screens. 

[The mobile flow can be found in the project Wiki](https://github.com/code4romania/teacher-workout-backend/wiki/Teacher-Workout-Mobile-flow).

_Please define related colors and text & button styles in the corresponding values files. Please extract all text values in the corresponding xml files so we can easily adjust them. <3_

---

The names of the lesson themes will be fetched from the corresponding endpoint in the backend. _(We will link the staging env for the backend and list the endpoint as soon as we define them)_

The search bar should only search though lesson theme titles. It will then only display lesson themes that contain the search keywords in the space below. If the search term is deleted, the list below will display all the themes once more. 

Pressing the **Descoperă** button in the footer also takes the user to his screen. On this screen, the  **Descoperă** button in the footer will have a highlight (it will be blue, instead of grey). 

![image](https://user-images.githubusercontent.com/14028425/123410275-ce314900-d5b7-11eb-9438-1aae9d8aca06.png)

Related:

- [x] https://github.com/code4romania/teacher-workout-android/issues/30
- [x] https://github.com/code4romania/teacher-workout-android/issues/29

**Comment by PanduruIonut** [comment]
I'm currently working on this.

**Comment by alexandru-calinoiu** [comment]
Here is the graphql query to populate this screen https://teacher.heroesof.tech/ui/graphiql?query=query%20%7B%0A%20%20themes%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20thumbnail%20%7B%0A%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D

**Comment by AlexandraDamaschin** [comment]
Here it might be better to split this into 2 PRs: one for implementing the UI as per design with dummy data and another PR in which we connect this screen to the API 

Let's keep this issue for implementing the basic UI of the screen and tackle the rest in future PRs.

**Comment by AlexandraDamaschin** [comment]
@PanduruIonut did you get the chance to make some progress on this? Would you still like to work on it? We can chat more about this if you want to decide on further steps.

**Comment by daniyelp** [comment]
@AlexandraDamaschin I could tackle this.

**Comment by AlexandraDamaschin** [comment]
Sure, feel free to tackle it :+1:

**Comment by daniyelp** [comment]
Should I put the title in a top bar? along with the search icon (that expands into a search view)?

**Comment by PanduruIonut** [comment]
Sorry for blocking this task, i had multiple issues with android studio on my device every time i tried to work on this. I think it would be better to be picked up by someone else.

**Comment by AlexandraDamaschin** [comment]
@daniyelp Not sure about which title you're asking. That's how the design looks like for the lesson themes 
![image](https://user-images.githubusercontent.com/29914519/141293606-66636eec-a1b6-415d-b1d6-3d9cf93c501f.png)
